name: Build Jenkins AMI

#on:
#  pull_request:
#    types: [ closed ]
#    branches:
#      - main

on:
  pull_request:
    branches: [ main ]

jobs:
  merge:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: latest

      - name: Run `packer init`
        id: init
        run: "packer init ./jenkins-ami.pkr.hcl"

      - name: Run `packer build`
        id: build
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.GHACTIONS_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.GHACTIONS_AWS_SECRET_ACCESS_KEY }}
        run: packer build \
          -var "profile=${{ secrets.GHACTIONS_JENKINS_AMI_PROFILE }}" \
          -var "ami_user=${{ secrets.GHACTIONS_JENKINS_AMI_USERS }}" \
          -var "jenkins_username=${{ secrets.GHACTIONS_JENKINS_USERNAME }}" \
          -var "jenkins_password=${{ secrets.GHACTIONS_JENKINS_PASSWORD }}" \
          ./jenkins-ami.pkr.hcl