name: Packer Validate

on:
  pull_request:
    branches: [ main ]

jobs:
  packer_validation:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: latest

      - name: Run `packer init`
        id: init
        run: "packer init ./jenkins-ami.pkr.hcl"

      - name: Run `packer validate`
        id: validate
        run: |
          if ! packer validate \
            -var "profile=${{ secrets.AWS_PROFILE }}" \
            -var "ami_user=${{ secrets.GHACTIONS_JENKINS_AMI_USERS }}" \ 
            -var "jenkins_username=${{ secrets.JENKINS_USERNAME }}" \ 
            -var "jenkins_password=${{ secrets.JENKINS_PASSWORD }}" \ 
            ./jenkins-ami.pkr.hcl ; then
            echo "Validation check failed"
            exit 1
          fi

      - name: Run `packer fmt`
        id: fmt
        run: |
          if ! packer fmt -check ./jenkins-ami.pkr.hcl ; then
            echo "Formatting check failed"
            exit 1
          fi
